DB2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^', include('authorization.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.Main.as_view(), name='main'),
    url(r'^search/(?P<search_str>[^\s]+)/$', views.SearchPage.as_view(), name='search'),
    url(r'^post_page/(?P<post_id>[0-9]+)/$', views.PostPage.as_view(), name='post_page'),
]  

main/models.py
from django.db import models
from django.contrib.auth.models import User
from authorization.models import CustomUser



def directory_path(instance, filename):
    
    return '{0}/{1}'.format(instance.user.id, instance.id)


class Like(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return "%s"%(self.user)


class Comment(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    comment = models.TextField()

    def __str__(self):
        return "%s %s"%(self.user, self.comment)


class Post(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=30)
    body = models.TextField()
    image = models.FileField(upload_to=directory_path)
    likes = models.ManyToManyField(Like, related_name = 'likes', blank=True, null=True)
    comments = models.ManyToManyField(Comment, related_name = 'comments', blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return "%s"%(self.title)

main/forms.py
from django import forms
from django.forms import TextInput, inlineformset_factory
from .models import Comment
# from main.models import 
from django.contrib.admin import widgets
# from django.forms.widgets import PasswordInput



class SearchForm(forms.Form):

    search = forms.CharField(widget=forms.TextInput(attrs={'class': 'w3-input w3-border',
                                                           'id': "search",
                                                           'placeholder': "search",
                                                           'style': "border:none; outline: none",
                                                           'autofocus': "none"}))


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': TextInput(attrs={
                    # 'class': 'w3-input w3-border w3-border-white', 
                    'placeholder': "comment",
            })
        }
    

main/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, Http404
from .models import Post, Like, Comment
from authorization.models import CustomUser
from .forms import SearchForm, CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

import re

class Search(object):    

    @staticmethod
    def sortByCountryOrCity(quary_set, complex_q):
        
        return quary_set.filter(complex_q)

    @staticmethod
    def createComplexQ(search_str, markers):
        list_to_search = re.findall(r"(\w+)", search_str)
        complex_q = Q()
        for item in list_to_search:
            for marker in markers:
                complex_q |= Q(**{marker: item})
            
        return complex_q

    

class PostActions(object):

    @staticmethod
    def likePost(request):

        post_id = int(request.POST['post_id'])
        user = CustomUser.objects.get(user=request.user)
        post = Post.objects.get(id=post_id)
        print(
            post_id,
            user,
            post,
        )
        try:
            like = post.likes.get(user=user)
            print(like)
            like.delete()

        except Like.DoesNotExist:
            post.likes.add(Like.objects.create(user=user))
            post.save()

        finally:
            return post

    @staticmethod
    def commentPost(request, post_id):

        post = Post.objects.get(id=post_id)

        comment_form = CommentForm(request.POST)
        
        if comment_form.is_valid():
            
            comment_data = comment_form.cleaned_data
            comment_data["user"] = CustomUser.objects.get(user=request.user)
            
            comment = Comment.objects.create(**comment_data)
            
            post.comments.add(comment)
            post.save()

            return post


class LoginRequiredView(LoginRequiredMixin, View):


    login_url = settings.LOGIN_URL
    redirect_field_name = settings.LOGIN_URL

# class MainPagination(object):

#     @staticmethod
#     def make_pagination(request, some_list=None, num_items=2):

#         paginator = Paginator(some_list, num_items) 
#         request = getattr(request, request.method)
#         page = request.get('page_number')
#         pages_list = [p for p in paginator.page_range]
#         print(pages_list)

#         try:
#             pags = paginator.page(page)
#         except PageNotAnInteger:
#             # If page is not an integer, deliver first page.
#             pags = paginator.page(1)
#         except EmptyPage:
#             # If page is out of range (e.g. 9999), deliver last page of results.
#             pags = paginator.page(paginator.num_items)

#         return pags, pages_list

class Main(LoginRequiredView):

    # def get(self, request):

    #     context = {}
    #     print(request.user)

    #     search_form = SearchForm()
    #     context['search_form'] = search_form
    #     posts = Post.objects.all()
    #     page = request.GET.get('pagination_page')

    #     context['post_pags'], context['post_pages_list'] = MainPagination.make_pagination(request, list(posts), 2)
        
    #     return render(request, "main.html", context)
    def get(self, request):

        context = {}
        print(request.user)

        search_form = SearchForm()
        context['search_form'] = search_form
        posts = Post.objects.all()
        pagination_page = request.GET.get('pagination_page')

        if pagination_page:
            pagination_page = int(pagination_page)

        paginator = Paginator(posts, 2) 

        try:
            posts_page = paginator.page(pagination_page)
        except PageNotAnInteger:
            posts_page = paginator.page(1)
        except EmptyPage:
            posts_page = paginator.page(paginator.num_items)

        context['posts_page'] = posts_page
        context['page_range'] = paginator.page_range
        
        
        return render(request, "main.html", context)

    def post(self, request):
        # print(request.POST.get("submit") == "pagination_page")
        if request.POST.get("submit") == "search":
            search_form = SearchForm(request.POST)
            if search_form.is_valid():
                search_data = search_form.cleaned_data
        
            return redirect("/search/%s/"%search_data["search"].replace(",","+").replace(" ",""))

        if request.is_ajax():
            print("is_ajax")
            post = PostActions.likePost(request)

            return HttpResponse("%s like"%post.likes.count())


class SearchPage(LoginRequiredView):

    def get(self, request, search_str):

        context = {}
        # search_str = request.GET.get('search')
        # print(search_str)
        print(re.findall(r"(\w+)", search_str))
        complex_q = Search.createComplexQ(search_str, ["country", "city"])
        posts = Post.objects.all()
        posts = Search.sortByCountryOrCity(posts, complex_q)

        search_form = SearchForm()
        context['search_form'] = search_form
        # posts = Post.objects.all()
        pagination_page = request.GET.get('pagination_page')

        if pagination_page:
            pagination_page = int(pagination_page)

        paginator = Paginator(posts, 2) 

        try:
            posts_page = paginator.page(pagination_page)
        except PageNotAnInteger:
            posts_page = paginator.page(1)
        except EmptyPage:
            posts_page = paginator.page(paginator.num_items)

        context['posts_page'] = posts_page
        context['page_range'] = paginator.page_range
        context['search_str'] = search_str
        
        return render(request, "search.html", context)

    def post(self, request, search_str):

        if request.POST.get("submit") == "search":
            search_form = SearchForm(request.POST)
            if search_form.is_valid():
                search_data = search_form.cleaned_data
        
            return redirect("/search/%s/"%search_data["search"].replace(",","+").replace(" ",""))

        if request.is_ajax():
            
            post = PostActions.likePost(request)

            return HttpResponse("%s like"%post.likes.count())

class PostPage(LoginRequiredView):


    def get(self, request, post_id):
        context = {}

        comment_form = CommentForm()
        context["comment_form"] = comment_form

        post = get_object_or_404(Post, id=post_id)
        context["post"] = post

        comments = post.comments.all().order_by("-id")
        context["comments"] = comments[:3]

        if comments.count() > 3:
            context["more"] = True

        return render(request, "post_page.html", context)

    def post(self, request, post_id):

        context = {}
        if request.POST.get("submit") == "comment":
            
            post = PostActions.commentPost(request, post_id)
            context["post"] = post

            return redirect("/post_page/%s/"%post_id)

        elif request.is_ajax():
            num = int(request.POST['num'])
            num += 2
            post_id = int(request.POST['post_id'])
            print(num)
            post = get_object_or_404(Post, id=post_id)
            context["post"] = post
            comments = post.comments.all().order_by("-id")
            context["comments"] = comments[:num]

            if comments.count() > num:
                context["more"] = True
            
            return render(request, "comments_ajax.html", context)

        else:
            return Http404


        # print("dsadassaddssa",request.is_ajax())
        # if request.is_ajax() and request.POST["flag"] == "add_comment":
        #     context = {}
        #     # post_id = request.POST["post_id"]
        #     print(post_id)
        #     post = PostActions.commentPost(request, int(post_id))
        #     context["post"] = post
        #     print(post)
        #     return render(request, "comments_ajax.html", context)
            

def more_comments(request):
    if request.is_ajax():
        num = request.POST['num']
        print(num)
        reviews = Review.objects.all().order_by("-id")[:int(num)]
        return render(request, "reviews.html", {"reviews": reviews})
    else:
        return Http404

main/templates/base_main.html
<!DOCTYPE html>
{% load static %}
<html>
<title>DB2</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script src="{% static 'main/libs/jquery-1.11.2.min.js' %}"></script>
<body>
<div class="w3-bar w3-green">
    
    <a href="/" class="w3-bar-item w3-button">MAIN</a>
    <a href="/sign_out/" class="w3-bar-item w3-button w3-right">LogOut</a>
    
</div>

{% block content %}
{% endblock %}


</body>
</html>
<script type="text/javascript">
    function goTo(url) {
        location.href = url
    }
    
    $(document).ready(function () {
        $(".posts").on("click", ".like", function() {
            var url = "/";
            var post_id = $(this).attr("post_id");
            var update = "#like_post_id_" + post_id;
            $.ajax({
                type: 'POST',
                async: true,
                url: url,
                data: {
                    'post_id': post_id,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success: function(data) {
                    $(update).html(data);
                },
                datatype: 'json',
            });
        });
    });
    $(document).ready(function () {
        $("#comments_ajax").on("click", "#more", function() {
            var post_id = $(this).attr("post_id");
            var url = "/post_page/" + post_id + "/";
            var num = $(this).attr("num");
            $.ajax({
                type: 'POST',
                async: true,
                url: url,
                data: {
                    'num': num,
                    'post_id': post_id,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success: function(data) {
                    $('#comments_ajax').html(data);
                },
                datatype: 'json',
            });
        });
    });
    
    // $(document).ready(function () {
    //     $("#post_comments").on("click", "#add_comment", function() {
    //         var post_id = $(this).attr("post_id");
    //         var url = "/post_page/" + post_id + "/";
    //         // var update = "#like_post_id_" + post_id;
    //         $.ajax({
    //             type: 'POST',
    //             async: true,
    //             url: url,
    //             data: {
    //                'csrfmiddlewaretoken': '{{csrf_token}}',
    //                'flag': 'add_comment',
    //                'post_id': post_id,
    //             },
    //             success: function(data) {
    //                 $("#comments_ajax").html(data);
    //             },
    //             datatype: 'json',
    //         });
    //     });
    // });
    
    
</script>

main/templates/comments_ajax.html
{% if comments.count > 0 %}
    {% for comment in comments.all %}
        <p>{{comment.user}} <span class="w3-small">{{comment.comment}}</span></p>
    {% endfor %}
    {% if more %}
    <div class="w3-padding-16 w3-center">
        <button class="w3-button w3-animate-zoom" id="more" post_id="{{post.id}}" num="{{comments.count}}">more<i class="w3-xxxlarge fa fa-chevron-down" aria-hidden="true"></i></button>
    </div>
    {% endif %}
{% endif %}

main/templates/main.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}
<div class="w3-container">
    <form method="post">{% csrf_token %}
        {{search_form.search}}
        <button class="w3-button w3-animate-zoom" next="{{ portfolio_pags.next_page_number }}" type="submit" name="submit" value="search" id="next_page">Search</button>
    </form>
    <!-- <form action="search/">
        {{search_form.search}}
        <button class="w3-button w3-animate-zoom" next="{{ portfolio_pags.next_page_number }}" type="submit" name="submit" value="search" id="next_page">Search</button>
    </form> -->
</div>
<!-- {{post_pages_list}} -->
<!-- <div class="w3-container">
    <div class="w3-content posts">
        <div class="w3-row-padding w3-margin-top">

        {% for post in post_pags %}

            <div class="w3-third">
                <div class="w3-card-2">
                    <div class="w3-content" style="cursor: pointer">
                        <img src="{{post.image.url}}" style="width:100%; height: 50vh;" onclick="goTo('{% url "main:post_page" post.id %}')" >
                    </div>
                    <div class="w3-container">
                        <h5><a href='{% url "main:post_page" post.id %}'>{{post.title}}</a> <span id="like_post_id_{{post.id}}" class="w3-right w3-button w3-padding-small like" post_id="{{post.id}}">{{post.likes.count}} like<i class="fa fa-heart" aria-hidden="true"></i></span></h5>
                    </div>
                    <div class="w3-container">
                        <p>{{post.body}}</p>
                    </div>
                </div>
                <br>
            </div>

        {% endfor %}
        </div>
    </div>
</div> -->

<div class="w3-container">
    <div class="w3-content posts">
        <div class="w3-row-padding w3-margin-top">

        {% for post in posts_page %}

            <div class="w3-third">
                <div class="w3-card-2">
                    <div class="w3-content" style="cursor: pointer">
                        <img src="{{post.image.url}}" style="width:100%; height: 50vh;" onclick="goTo('{% url "main:post_page" post.id %}')" >
                    </div>
                    <div class="w3-container">
                        <h5><a href='{% url "main:post_page" post.id %}'>{{post.title}}</a> <span id="like_post_id_{{post.id}}" class="w3-right w3-button w3-padding-small like" post_id="{{post.id}}">{{post.likes.count}} like<i class="fa fa-heart" aria-hidden="true"></i></span></h5>
                    </div>
                    <div class="w3-container">
                        <p>{{post.body}}</p>
                    </div>
                </div>
                <br>
            </div>

        {% endfor %}
        </div>
    </div>
</div>

<!-- <div class="w3-container" >
    <div class="w3-content w3-center w3-padding-32">
        
        <div class="w3-section">
        
        {% if post_pags.has_previous %}
        <form method="post" >{% csrf_token %}
            
            <input type="hidden" name="page_number" value="{{ portfolio_pags.previous_page_number }}">
            <button class="w3-button w3-animate-zoom" prev="{{ portfolio_pags.previous_page_number }}" type="submit" name="submit" value="pagination_page" id="prev_page">prev<i class="w3-xxxlarge fa fa-chevron-left" aria-hidden="true"></i></button>
        </form>
        {% endif %}
        

        {% for p in post_pages_list %}
        <form method="post" >{% csrf_token %}
            
            <input type="hidden" name="page_number" value="{{ p }}">
            <button class="w3-button w3-green w3-opacity-min w3-round-xlarge" type="submit" name="submit" value="pagination_page">
                {{p}}
            </button>
        </form>
        {% endfor %}
        {% if post_pags.has_next %}
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            
            <input type="hidden" name="page_number" value="{{ portfolio_pags.next_page_number }}">
            <button class="w3-button w3-animate-zoom" next="{{ portfolio_pags.next_page_number }}" type="submit" name="submit" value="pagination_page" id="next_page">next<i class="w3-xxxlarge fa fa-chevron-right" aria-hidden="true"></i></button>
        </form>
        {% endif %}
        
        </div>
        
    </div>
</div> -->

<div class="w3-container" >
    <div class="w3-content w3-center w3-padding-32">
        
        <div class="w3-section">
        
        {% if posts_page.has_previous %}
        
            <button class="w3-button w3-animate-zoom" onclick="goTo('{% url "main:main" %}?pagination_page={{ posts_page.previous_page_number }}')">prev<i class="w3-xxxlarge fa fa-chevron-left" aria-hidden="true"></i></button>
        
        {% endif %}
        

        {% for page_number in page_range %}
        
            <button class="w3-button w3-green w3-opacity-min w3-round-xlarge" onclick="goTo('{% url "main:main" %}?pagination_page={{page_number}}')">
                {{page_number}}
            </button>
        
        {% endfor %}
        {% if posts_page.has_next %}
        
            <button class="w3-button w3-animate-zoom" onclick="goTo('{% url "main:main" %}?pagination_page={{ posts_page.next_page_number }}')">next<i class="w3-xxxlarge fa fa-chevron-right" aria-hidden="true"></i></button>
        
        {% endif %}
        
        </div>
        
    </div>
</div>
<!-- {{post_pags}} -->

{% endblock %}

main/templates/post_page.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}

<!-- {{post_pages_list}} -->

<div class="w3-content w3-padding-32 posts">
    <div class="w3-card-2" style="width:50vh;">
            
        <img src="{{post.image.url}}" style="width:50vh;">
        <div class="w3-container">
            <h5>{{post.title}}<span id="like_post_id_{{post.id}}" class="w3-right w3-button w3-padding-small like" post_id="{{post.id}}">{{post.likes.count}} like<i class="fa fa-heart" aria-hidden="true"></i></span></h5>
        </div>
        <div class="w3-container">
            <p>{{post.body}}</p>
        </div>
        <div class="w3-container" id="comments_ajax">
            {% include 'comments_ajax.html' %}
            <hr>            
        </div>

        <div lass="w3-container" id="post_comments">
            <form method="post">{% csrf_token %}
                <div class="w3-padding">{{comment_form.comment}}<span class="w3-right"><button id="add_comment" post_id="{{post.id}}" class="w3-button w3-padding-small " type="submit" name="submit" value="comment">
                    <i class="fa fa-paper-plane"></i> Comment
                </button></span></div>
                
            </form>
        </div>
    </div>
</div>




<!-- {{post_pags}} -->
{% endblock %}

main/templates/search.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}
<div class="w3-container">
    <form method="post">{% csrf_token %}
        {{search_form.search}}
        <button class="w3-button w3-animate-zoom" next="{{ portfolio_pags.next_page_number }}" type="submit" name="submit" value="search" id="next_page">Search</button>
    </form>
    <!-- <form action="search/">
        {{search_form.search}}
        <button class="w3-button w3-animate-zoom" next="{{ portfolio_pags.next_page_number }}" type="submit" name="submit" value="search" id="next_page">Search</button>
    </form> -->
</div>
<!-- {{post_pages_list}} -->
<!-- <div class="w3-container">
    <div class="w3-content posts">
        <div class="w3-row-padding w3-margin-top">

        {% for post in post_pags %}

            <div class="w3-third">
                <div class="w3-card-2">
                    <div class="w3-content" style="cursor: pointer">
                        <img src="{{post.image.url}}" style="width:100%; height: 50vh;" onclick="goTo('{% url "main:post_page" post.id %}')" >
                    </div>
                    <div class="w3-container">
                        <h5><a href='{% url "main:post_page" post.id %}'>{{post.title}}</a> <span id="like_post_id_{{post.id}}" class="w3-right w3-button w3-padding-small like" post_id="{{post.id}}">{{post.likes.count}} like<i class="fa fa-heart" aria-hidden="true"></i></span></h5>
                    </div>
                    <div class="w3-container">
                        <p>{{post.body}}</p>
                    </div>
                </div>
                <br>
            </div>

        {% endfor %}
        </div>
    </div>
</div> -->

<div class="w3-container">
    <div class="w3-content posts">
        <div class="w3-row-padding w3-margin-top">

        {% for post in posts_page %}

            <div class="w3-third">
                <div class="w3-card-2">
                    <div class="w3-content" style="cursor: pointer">
                        <img src="{{post.image.url}}" style="width:100%; height: 50vh;" onclick="goTo('{% url "main:post_page" post.id %}')" >
                    </div>
                    <div class="w3-container">
                        <h5><a href='{% url "main:post_page" post.id %}'>{{post.title}}</a> <span id="like_post_id_{{post.id}}" class="w3-right w3-button w3-padding-small like" post_id="{{post.id}}">{{post.likes.count}} like<i class="fa fa-heart" aria-hidden="true"></i></span></h5>
                    </div>
                    <div class="w3-container">
                        <p>{{post.body}}</p>
                    </div>
                </div>
                <br>
            </div>

        {% endfor %}
        </div>
    </div>
</div>

<!-- <div class="w3-container" >
    <div class="w3-content w3-center w3-padding-32">
        
        <div class="w3-section">
        
        {% if post_pags.has_previous %}
        <form method="post" >{% csrf_token %}
            
            <input type="hidden" name="page_number" value="{{ portfolio_pags.previous_page_number }}">
            <button class="w3-button w3-animate-zoom" prev="{{ portfolio_pags.previous_page_number }}" type="submit" name="submit" value="pagination_page" id="prev_page">prev<i class="w3-xxxlarge fa fa-chevron-left" aria-hidden="true"></i></button>
        </form>
        {% endif %}
        

        {% for p in post_pages_list %}
        <form method="post" >{% csrf_token %}
            
            <input type="hidden" name="page_number" value="{{ p }}">
            <button class="w3-button w3-green w3-opacity-min w3-round-xlarge" type="submit" name="submit" value="pagination_page">
                {{p}}
            </button>
        </form>
        {% endfor %}
        {% if post_pags.has_next %}
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            
            <input type="hidden" name="page_number" value="{{ portfolio_pags.next_page_number }}">
            <button class="w3-button w3-animate-zoom" next="{{ portfolio_pags.next_page_number }}" type="submit" name="submit" value="pagination_page" id="next_page">next<i class="w3-xxxlarge fa fa-chevron-right" aria-hidden="true"></i></button>
        </form>
        {% endif %}
        
        </div>
        
    </div>
</div> -->

<div class="w3-container" >
    <div class="w3-content w3-center w3-padding-32">
        
        <div class="w3-section">
        
        {% if posts_page.has_previous %}
        
            <button class="w3-button w3-animate-zoom" onclick="goTo('{% url "main:search" search_str %}?pagination_page={{ posts_page.previous_page_number }}')">prev<i class="w3-xxxlarge fa fa-chevron-left" aria-hidden="true"></i></button>
        
        {% endif %}
        

        {% for page_number in page_range %}
        
            <button class="w3-button w3-green w3-opacity-min w3-round-xlarge" onclick="goTo('{% url "main:search" search_str %}?pagination_page={{page_number}}')">
                {{page_number}}
            </button>
        
        {% endfor %}
        {% if posts_page.has_next %}
        
            <button class="w3-button w3-animate-zoom" onclick="goTo('{% url "main:search" search_str %}?pagination_page={{ posts_page.next_page_number }}')">next<i class="w3-xxxlarge fa fa-chevron-right" aria-hidden="true"></i></button>
        
        {% endif %}
        
        </div>
        
    </div>
</div>
<!-- {{post_pags}} -->

{% endblock %}